<a href="https://colab.research.google.com/github/rostovcevartem209/NumPy/blob/main/NumPy_teach.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

ИНДЕКСАЦИЯ И СРЕЗЫ

In [1]:
import numpy as np

arr1 = np.arange(10)
arr1
arr1[2]
arr1[-1]
arr1[3:8]

array([3, 4, 5, 6, 7])

In [2]:
arr2 = np.array([[1,2,3,4],
                 [5,6,7,8],
                 [9,10,11,12],
                 [13,14,15,16]])
print(arr2)
arr2[1,2]
arr2[0]
arr2[:,2]
arr2[:2,:2]

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


array([[1, 2],
       [5, 6]])

In [3]:
arr3 = np.arange(20)
arr3[::2]
arr3[2:15:3]
arr3[::-1]

array([19, 18, 17, 16, 15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,
        2,  1,  0])

In [4]:
image = np.random.randint(0,256,size = (8,8))
print(image)
image[2:6,2:6] #центральный квадрат 4x4
image[0:8:7]  #первая и последняя строка при помощи срезов
image[1::2,::2] #четные строки и нечетные столбцы

[[ 21  13 124  73 173 242  33  26]
 [ 72 236  83  98 217 134 121 189]
 [122 241 224  59 169 182 145 134]
 [  8  92  85  27 116 191 159 223]
 [196 207 188  89 238 198  56 202]
 [ 10  49 106  34 222   2 184 231]
 [145 171  67  55 159 125   5   9]
 [ 94  59 210 201  66 116  24  77]]


array([[ 72,  83, 217, 121],
       [  8,  85, 116, 159],
       [ 10, 106, 222, 184],
       [ 94, 210,  66,  24]])

In [5]:
original = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(original)
slice_viev = original[0:2,0:2]
slice_viev[0,0] = 100
print(original)
slice_copy = original.copy()
slice_copy[0,0] = 200
print(slice_copy)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[100   2   3]
 [  4   5   6]
 [  7   8   9]]
[[200   2   3]
 [  4   5   6]
 [  7   8   9]]


In [6]:
chess = np.zeros((8,8), dtype = int)
chess[0:8:2, 0:8:2] = 1
chess[1:8:2,1:8:2] = 1
chess

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]])

In [7]:
X = np.array([
    [10, 15, 20],
    [2, 30, 25],
    [15, 5, 12],
    [8, 18, 22],
    [3, 12, 8]
])
min_row = X.min(axis = 1, keepdims=True)
max_row = X.max(axis = 1, keepdims=True)
X = (X - min_row) / (max_row-min_row)
print(X)

[[0.         0.5        1.        ]
 [0.         1.         0.82142857]
 [1.         0.         0.7       ]
 [0.         0.71428571 1.        ]
 [0.         1.         0.55555556]]


In [8]:
temperature = np.random.normal(20, 5, size=30).round(1)
print("Температура за месяц:", temperature)
res = []
for i in range(1, len(temperature)-1):
  window = np.mean(temperature[i-1:i+2])
  res.append(round(window,1))
print(*res)


Температура за месяц: [17.1 27.9 21.5 16.6 20.5 31.  16.6 24.5 21.1 25.  15.7 14.3 20.2 24.4
 21.3 23.5 13.8 12.5 20.7 19.9 23.6 27.8 15.5 18.1 20.6 17.5 16.  22.8
 19.3 22.2]
22.2 22.0 19.5 22.7 22.7 24.0 20.7 23.5 20.6 18.3 16.7 19.6 22.0 23.1 19.5 16.6 15.7 17.7 21.4 23.8 22.3 20.5 18.1 18.7 18.0 18.8 19.4 21.4


In [9]:
code = np.array([
    [10, 99, 23, 45, 78],
    [34, 56, 12, 89, 31],
    [67, 43, 21, 76, 54],
    [98, 32, 65, 87, 19],
    [44, 55, 66, 77, 88]
])

a = code[0]
b = code[:,-1][::-1]
c = np.diag(code)
d = np.diag(np.fliplr(code))
res = np.concatenate([a,b,c,d])
print(res[10])

10


БУЛЕВА ИНДЕКСАЦИЯ

In [10]:
import numpy as np

np.random.seed(42)
arr = np.random.randint(0,20,size=15)
print(arr)
mask1 = arr>10
mask2 = arr%2==0
print(arr[mask1])
print(arr[mask2])

[ 6 19 14 10  7  6 18 10 10  3  7  2  1 11  5]
[19 14 18 11]
[ 6 14 10  6 18 10 10  2]


In [11]:
np.random.seed(42)
arr = np.random.randint(-10,10,size=20)
print(arr)
mask1 = (arr%2==0) & (arr<0)
mask2 = (arr>0) | (arr==0)
mask3 = arr!=5
print(arr[mask1])
print(arr[mask2])
print(arr[mask3])

[ -4   9   4   0  -3  -4   8   0   0  -7  -3  -8  -9   1  -5  -9 -10   1
   1   6]
[ -4  -4  -8 -10]
[9 4 0 8 0 0 1 1 1 6]
[ -4   9   4   0  -3  -4   8   0   0  -7  -3  -8  -9   1  -5  -9 -10   1
   1   6]


In [12]:
np.random.seed(42)
temperatures = np.random.uniform(-5,5,10)
print(temperatures)
temperatures[temperatures<0]=0
temperatures[temperatures>4]=4
print(temperatures)

[-1.25459881  4.50714306  2.31993942  0.98658484 -3.4398136  -3.4400548
 -4.41916388  3.66176146  1.01115012  2.08072578]
[0.         4.         2.31993942 0.98658484 0.         0.
 0.         3.66176146 1.01115012 2.08072578]


In [13]:
np.random.seed(42)
matrix = np.random.rand(5,5)
print(matrix)
mask1 = matrix[:,:]>0.5
mask2 = matrix[:,:]>=0.3

rows,cols = np.indices(matrix.shape)
mask3 = (rows == 0) | (rows == matrix.shape[0]-1) | (cols == 0) | (cols == matrix.shape[1]-1)

matrix[mask3]=-1
print(matrix)

[[0.37454012 0.95071431 0.73199394 0.59865848 0.15601864]
 [0.15599452 0.05808361 0.86617615 0.60111501 0.70807258]
 [0.02058449 0.96990985 0.83244264 0.21233911 0.18182497]
 [0.18340451 0.30424224 0.52475643 0.43194502 0.29122914]
 [0.61185289 0.13949386 0.29214465 0.36636184 0.45606998]]
[[-1.         -1.         -1.         -1.         -1.        ]
 [-1.          0.05808361  0.86617615  0.60111501 -1.        ]
 [-1.          0.96990985  0.83244264  0.21233911 -1.        ]
 [-1.          0.30424224  0.52475643  0.43194502 -1.        ]
 [-1.         -1.         -1.         -1.         -1.        ]]


In [14]:
np.random.seed(42)
ages = np.random.randint(18,26,7)
scores = np.random.randint(0,101,7)
sleep = np.random.randint(4,11,7)
students = np.column_stack((ages,scores,sleep))
mask_score = students[:,1]>=60
mask_sleep = students[:,2]>8
mask_ages = students[:,0]>21
print(students)
print()
print(students[mask_sleep])
print(np.mean(students[mask_sleep][:,1]))

[[24 20  6]
 [21 82  9]
 [22 86  8]
 [24 74  5]
 [20 74  7]
 [25 87  9]
 [22 99  9]]

[[21 82  9]
 [25 87  9]
 [22 99  9]]
89.33333333333333


УНИВЕРСАЛЬНЫЕ ФУНКЦИИ И АГРЕГАЦИЯ

In [15]:
import numpy as np

a = np.array([10,20,30,40,50])
b = np.array([1,2,3,4,5])

a*b
a/b
a**b
a>25

array([False, False,  True,  True,  True])

In [16]:
import math as m
corners = np.linspace(0,2*m.pi,20)

np.sin(corners)
np.cos(corners)
exp = np.exp(np.array([1,2,3]))
log = np.log(np.array([1, np.e, np.e**2]))

In [17]:
np.random.seed(42)
data = np.random.randint(1,100,size = (5,5))
print(data)
total_sum = np.sum(data)
min_arg = np.min(data)
max_arg = np.max(data)
mean = np.mean(data)
std = np.std(data)
median = np.median(data)

index = np.unravel_index(np.argmax(data), data.shape)

[[52 93 15 72 61]
 [21 83 87 75 75]
 [88 24  3 22 53]
 [ 2 88 30 38  2]
 [64 60 21 33 76]]


In [18]:
np.random.seed(42)
data = np.random.randint(1,100,size = (5,5))
print(data)
sum_cols = np.sum(data,axis = 0)
sum_rows = np.sum(data, axis = 1)
min_from_rows = np.min(data, axis = 1)

[[52 93 15 72 61]
 [21 83 87 75 75]
 [88 24  3 22 53]
 [ 2 88 30 38  2]
 [64 60 21 33 76]]


In [19]:
np.random.seed(42)
x = np.random.rand(10,3)
mean_x = np.mean(x, axis = 0)
x = x - mean_x
mean = np.mean(x, axis = 0)
print(mean_x)
print(mean)

[0.42969452 0.44710393 0.43899337]
[ 5.55111512e-17 -1.66533454e-17 -3.33066907e-17]


In [20]:
np.random.seed(42)
x = np.random.rand(10,3)
min_from_cols = np.min(x, axis = 0)
max_from_cols = np.max(x, axis = 0)
print(x)
print()
# print(min_from_cols)
# print(max_from_cols)
x = (x-min_from_cols)/(max_from_cols-min_from_cols)
print(x)

[[0.37454012 0.95071431 0.73199394]
 [0.59865848 0.15601864 0.15599452]
 [0.05808361 0.86617615 0.60111501]
 [0.70807258 0.02058449 0.96990985]
 [0.83244264 0.21233911 0.18182497]
 [0.18340451 0.30424224 0.52475643]
 [0.43194502 0.29122914 0.61185289]
 [0.13949386 0.29214465 0.36636184]
 [0.45606998 0.78517596 0.19967378]
 [0.51423444 0.59241457 0.04645041]]

[[0.40866897 1.         0.74236453]
 [0.69809333 0.14560779 0.11862363]
 [0.         0.90911144 0.60063775]
 [0.83938966 0.         1.        ]
 [1.         0.20615898 0.14659502]
 [0.16183823 0.30496576 0.51795022]
 [0.48280112 0.29097513 0.61226564]
 [0.10513243 0.29195941 0.34642716]
 [0.51395587 0.82202662 0.16592323]
 [0.58906891 0.61478523 0.        ]]


ИЗМЕНЕНИЕ ФОРМЫ И ТРАНСФОРМАЦИЯ ДАННЫХ

In [21]:
import numpy as np

arr = np.arange(12)
matrix_3x4 = arr.reshape(3,4)
matrix_4x3 = matrix_3x4.reshape(4,3)
tenzor = arr.reshape(2,3,2)

In [22]:
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
flat = matrix.flatten() #копирование матрицы
raw = matrix.ravel() #представление матрицы

flat[0]=999
raw[0]=888
print(matrix)

[[888   2   3]
 [  4   5   6]
 [  7   8   9]]


In [23]:
a = np.array([10,20,30,40])
res = a.reshape(-1,1)
res1 = a.reshape(1,-1)
b = np.array([[[1], [2], [3]]])
res = np.squeeze(b)
print(b.shape)
print(res)

(1, 3, 1)
[1 2 3]


In [24]:
x = np.array([[1,2,3],[4,5,6]])
print(x)
transp = x.T
print(transp)

res = x@transp #матрица грама для объектов

res1 = transp@x #матрица грама для признаков

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]


In [25]:
a = np.ones((3,3))
b = np.zeros((3,3))

res1 = np.vstack([a,b]) #добавляет строки(объекты)
res2 = np.hstack([a,b]) #добавляет столбцы(признаки)

x = [1,2,3]
y = [4,5,6]
res3 = np.vstack([x,y])
res4 = np.column_stack([x,y]) #собирает матрцу по столбцам
print(res4)

[[1 4]
 [2 5]
 [3 6]]


In [26]:
np.random.seed(42)

data = np.arange(20)
res = np.split(data,4) #деление по количеству элементов
res1 = np.split(data, [5,15]) #деление по индексам

matrix = np.random.randint(0,100,size = (10,5))
res2 = np.hsplit(matrix, [4]) #делит матрицу по вертикали
res3 = np.vsplit(matrix, [4]) #делит матрицу по горизонтали

ЛИНЕЙНАЯ АЛГЕБРА И ГЕНЕРАЦИЯ СЛУЧАЙНЫХ ЧИСЕЛ

In [27]:
import numpy as np

a = np.array([[1, 2], [3, 4], [5, 6]])
b = np.array([[7, 8, 9, 10], [11, 12, 13, 14]])
res = a@b #перемножение матриц

v = np.array([1, 2, 3]) #вектор строка
w = np.array([4, 5, 6]) #вектор столбец
skal = v@w #для одномерных массивов вычисляется скалярное произведение

In [28]:
a = np.array([[2,1],[1,-3]])
b = np.array([5,-8])
solutions = np.linalg.solve(a,b)

#решение систем уравнений

c = np.array([[1,2,1],[1,-1,2],[1,1,-1]])
d = np.array([6,3,3])
solv = np.linalg.solve(c,d)

In [29]:
M = np.array([[4, 7], [2, 6]])
det = np.linalg.det(M) #определитель матрицы
M_inv = np.linalg.inv(M) #вычисление обратной матрицы

In [30]:
s = np.array([[5,2],[2,4]])
eingvalues, eingvector = np.linalg.eig(s)

print(s@eingvector[:,0])
print(s[0]*eingvector[:,0]) #собственные векторы и значения??????????

[5.17185161 4.03805971]
[3.94102719 1.23082442]


In [31]:
p = np.array([1, 2, 3])
q = np.array([4, 5, 6])

np.linalg.norm(p) #длина вектора
np.linalg.norm(p-q) #расстояние между точками
np.linalg.norm(p, ord=1) #манхеттенское расстояние (dist = |x1-x2|+|y1-y2|)
np.linalg.norm(p-q, ord = np.inf) #расстояние чебышева (dist = max(|x1-x2|,|y1-y2|)

np.float64(3.0)

In [32]:
np.random.seed(42)

random_int = np.random.randint(1,11,5)
rr_matrix = np.random.rand(3,3) #равномерное распределение
nr_matrix = np.random.randn(4,2) #нормальное распределение
normal_mas = np.random.normal(100,15,100) #массив со средним 100 и стандартным отклонением 15


In [33]:
np.random.seed(42)

data = np.arange(20)
np.random.shuffle(data)

#перемешивание двух связаных массивов (x(100 объектов, 5 признаков), y(100 доп. признаков к x))
x = np.random.randn(100, 5)
y = np.random.randn(100)

indices = np.arange(100)
np.random.shuffle(indices)
x_shuff = x[indices]
y_shuff = y[indices]

#формирование выборки
np.random.choice(data,5,replace = False) #выборка 5 элементов без повторений
np.random.choice(data,5, replace = True) #выборка с повторением

#взвешенная выборка (вероятность событий не равна и задается аргументом)
np.random.choice(['A', 'B', 'C'], size=20, p = [0.9,0.05,0.05])

array(['A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A',
       'A', 'A', 'A', 'C', 'A', 'A', 'A'], dtype='<U1')

In [34]:
np.random.seed(42)

X = np.random.randn(100,3) #100 объектов 3 признака
w_true = np.array([2.5,-1.3,0.8]) #истинные веса (коэфициенты влияющие на целевую переменную)
noise = np.random.normal(0,0.5,100) #шум (помехи, наличие которых симулирует настоящие данные)

y = X@w_true+noise #целевые переменные

#связно перемешиваем данные (y[0] всё также является целевым значением x[0])
indices = np.arange(100)
X_shuffle = X[indices]
y_shuffle = y[indices]

#делим данные на тренировочные и тестовые
split_ind = 80
X_train, X_test = X_shuffle[:split_ind], X_shuffle[split_ind:]
y_train, y_test = y_shuffle[:split_ind], y_shuffle[split_ind:]

#обучение модели через lstsq (????)
w_estimated = np.linalg.lstsq(X_train,y_train,rcond=None)[0]

#предсказываем целевые значения
y_pred = X_test@w_estimated

#считаем среднюю квадратичную ошибку
mse = np.mean((y_pred-y_test)**2)
print(mse)

0.3193057296384286


ФИНАЛЬНЫЙ ПРОЕКТ

In [35]:
import numpy as np
np.random.seed(42)
n = 500

area = np.random.uniform(30,120,n)
rooms = np.random.randint(1,5,n)
floor = np.random.uniform(0,1,n)
year_build = np.random.randint(1980,2025,n)
dist_underground = np.random.uniform(0,3,n)

x = np.column_stack([area, rooms, floor, year_build, dist_underground])

w_true = np.array([2.5,    # каждый м² добавляет 2.5 млн руб
                   3.0,    # каждая комната добавляет 3 млн руб
                   -1.5,   # высокий этаж (ближе к последнему) снижает цену
                   0.08,   # каждый год новее добавляет 0.08 млн (80 тыс)
                   -2.0])  # каждый км до метро снижает цену на 2 млн

b_true = -150 #свободный член (bias)

y_ideal = x@w_true+b_true #цены квартир

#добавление шума
noise_std = 5
noise = np.random.normal(0,noise_std,n)
y = y_ideal+noise

print('='*60)
print('Данные сгенерированы')
print('='*60)
print(f'Форма x: {x.shape}')
print(f'Форма y: {y.shape}')
print(f'Истинные веса: {w_true}')
print(f'Стандартное отклонение шума {noise.std()}')
print(f'Диапазон цен: от {y.min()} до {y.max()}')

Данные сгенерированы
Форма x: (500, 5)
Форма y: (500,)
Истинные веса: [ 2.5   3.   -1.5   0.08 -2.  ]
Стандартное отклонение шума 5.089832041520238
Диапазон цен: от 84.7085845246495 до 327.6735272198148


In [36]:
print('='*60)
print('Статистическое описание признаков')
print('='*60)

feature_names = ['Площадь', 'Комнатность', 'Этаж', 'Год постройки', 'Расстояние до метро']
for name, feature in zip(feature_names, x.T):
  print(f'\n{name.upper()}')
  print(f'Среднее: {np.mean(feature)}')
  print(f'Стандартное отклонение: {np.std(feature)}')
  print(f'Минимальное значение: {np.min(feature)}')
  print(f'Максимальное значение: {np.max(feature)}')

print('\n','='*60)
print('Вычисление корреляции с ценой')
print('='*60)
for name, feature in zip(feature_names, x.T):
  corr = np.corrcoef(feature, y)[0,1]
  print(f'\n{name}: {corr}')

Статистическое описание признаков

ПЛОЩАДЬ
Среднее: 74.87055410106124
Стандартное отклонение: 26.855061345850093
Минимальное значение: 30.45554254615968
Максимальное значение: 119.36683165073703

КОМНАТНОСТЬ
Среднее: 2.386
Стандартное отклонение: 1.0885788901131603
Минимальное значение: 1.0
Максимальное значение: 4.0

ЭТАЖ
Среднее: 0.5081090388607892
Стандартное отклонение: 0.2954815576256474
Минимальное значение: 0.004632023004602859
Максимальное значение: 0.9979341105333375

ГОД ПОСТРОЙКИ
Среднее: 2002.046
Стандартное отклонение: 13.01368064768765
Минимальное значение: 1980.0
Максимальное значение: 2024.0

РАССТОЯНИЕ ДО МЕТРО
Среднее: 1.4505437730747963
Стандартное отклонение: 0.8573609349230278
Минимальное значение: 0.0009975183614682193
Максимальное значение: 2.9864414721127712

Вычисление корреляции с ценой

Площадь: 0.9957180216413284

Комнатность: 0.08112194028718915

Этаж: 0.06986521972415496

Год постройки: 0.0009393633783435306

Расстояние до метро: -0.05955973904228864


In [37]:
x_with_bias = np.column_stack([np.ones(n), x])
#перемешиваем данные
indicies = np.arange(n)
np.random.shuffle(indicies)
x_shuffle = x_with_bias[indicies]
y_shuffle = y[indicies]

#делим данные на обучающие и тестовые
split_idx = int(0.8*n)
x_train, x_test = x_shuffle[:split_idx], x_shuffle[split_idx:]
y_train, y_test = y_shuffle[:split_idx], y_shuffle[split_idx:]

#нормализация признаков
#среднее значение и отклонение используем только из обучающей выборки
mean_x_train = np.mean(x_train[:,1:], axis = 0)
std_x_train = np.std(x_train[:,1:], axis = 0)

normal_x_train = x_train.copy()
normal_x_test = x_test.copy()

normal_x_train[:,1:] = (x_train[:,1:]-mean_x_train)/std_x_train
normal_x_test[:,1:] = (x_test[:,1:]-mean_x_train)/std_x_train

print(np.std(normal_x_train[:,1:], axis = 0))

[1. 1. 1. 1. 1.]


In [38]:
print('='*60)
print('Результаты обучения модели')
print('='*60)
w_estimated = np.linalg.lstsq(normal_x_train,y_train,rcond=None)[0]

b_estimated = w_estimated[0]
w_feature_estimated = w_estimated[1:]

w_original_scale = w_feature_estimated / std_x_train
b_original_scale = b_estimated - np.sum(mean_x_train * w_feature_estimated / std_x_train)

print(f'Свободный член (bias): {b_estimated:.2f}')
print('Веса признаков')
for name, w_true_val, w_rec in zip(feature_names, w_true, w_original_scale):
    diff = abs(w_true_val - w_rec)
    print(f"{name:<20} | {w_true_val:10.2f} | {w_rec:15.4f} | {diff:10.4f}")

print(f"\n{'Bias':<20} | {b_true:10.2f} | {b_original_scale:15.4f} | {abs(b_true - b_original_scale):10.4f}")

Результаты обучения модели
Свободный член (bias): 201.50
Веса признаков
Площадь              |       2.50 |          2.4801 |     0.0199
Комнатность          |       3.00 |          3.0168 |     0.0168
Этаж                 |      -1.50 |         -0.9928 |     0.5072
Год постройки        |       0.08 |          0.0724 |     0.0076
Расстояние до метро  |      -2.00 |         -1.5352 |     0.4648

Bias                 |    -150.00 |       -133.9495 |    16.0505


In [41]:
!apt-get install git
!git clone https://github.com/rostovcevartem209/NumPy.git
%cd NumPy

Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
git is already the newest version (1:2.34.1-1ubuntu1.17).
0 upgraded, 0 newly installed, 0 to remove and 6 not upgraded.
fatal: destination path 'NumPy' already exists and is not an empty directory.
/content/NumPy
