<a href="https://colab.research.google.com/github/rostovcevartem209/NumPy/blob/main/NumPy_teach.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

ИНДЕКСАЦИЯ И СРЕЗЫ

In [ ]:
import numpy as np

arr1 = np.arange(10)
arr1
arr1[2]
arr1[-1]
arr1[3:8]

array([3, 4, 5, 6, 7])

In [ ]:
arr2 = np.array([[1,2,3,4],
                 [5,6,7,8],
                 [9,10,11,12],
                 [13,14,15,16]])
print(arr2)
arr2[1,2]
arr2[0]
arr2[:,2]
arr2[:2,:2]

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


array([[1, 2],
       [5, 6]])

In [ ]:
arr3 = np.arange(20)
arr3[::2]
arr3[2:15:3]
arr3[::-1]

array([19, 18, 17, 16, 15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,
        2,  1,  0])

In [ ]:
image = np.random.randint(0,256,size = (8,8))
print(image)
image[2:6,2:6] #центральный квадрат 4x4
image[0:8:7]  #первая и последняя строка при помощи срезов
image[1::2,::2] #четные строки и нечетные столбцы

[[ 89  17  90  12 107 156  16 141]
 [164  40 198  17 138 171 167 115]
 [123 238 229 216 179   3 115 190]
 [155 111 120   4 245 140 216 205]
 [ 96  65  38  21  12  58 245 245]
 [175 198 218 163 201 232 165 186]
 [ 25 116  26  68 149 138  48 151]
 [  6 250  16 157 154 163   4  95]]
[[164 198 138 167]
 [155 120 245 216]
 [175 218 201 165]
 [  6  16 154   4]]


In [ ]:
original = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(original)
slice_viev = original[0:2,0:2]
slice_viev[0,0] = 100
print(original)
slice_copy = original.copy()
slice_copy[0,0] = 200
print(slice_copy)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[100   2   3]
 [  4   5   6]
 [  7   8   9]]
[[200   2   3]
 [  4   5   6]
 [  7   8   9]]


In [ ]:
chess = np.zeros((8,8), dtype = int)
chess[0:8:2, 0:8:2] = 1
chess[1:8:2,1:8:2] = 1
chess

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]])

In [ ]:
X = np.array([
    [10, 15, 20],
    [2, 30, 25],
    [15, 5, 12],
    [8, 18, 22],
    [3, 12, 8]
])
min_row = X.min(axis = 1, keepdims=True)
max_row = X.max(axis = 1, keepdims=True)
X = (X - min_row) / (max_row-min_row)
print(X)

[[0.         0.5        1.        ]
 [0.         1.         0.82142857]
 [1.         0.         0.7       ]
 [0.         0.71428571 1.        ]
 [0.         1.         0.55555556]]


In [ ]:
temperature = np.random.normal(20, 5, size=30).round(1)
print("Температура за месяц:", temperature)
res = []
for i in range(1, len(temperature)-1):
  window = np.mean(temperature[i-1:i+2])
  res.append(round(window,1))
print(*res)


Температура за месяц: [18.3 20.  22.5 20.9 17.5 23.6 27.8 25.8 18.9  9.8 20.1 22.7 15.6 24.6
 16.2 18.5 24.8 16.4 12.1 15.2 24.7 13.9 18.1 17.9 14.1 29.4 25.4 19.8
 16.6 16.9]
20.3 21.1 20.3 20.7 23.0 25.7 24.2 18.2 16.3 17.5 19.5 21.0 18.8 19.8 19.8 19.9 17.8 14.6 17.3 17.9 18.9 16.6 16.7 20.5 23.0 24.9 20.6 17.8


In [ ]:
code = np.array([
    [10, 99, 23, 45, 78],
    [34, 56, 12, 89, 31],
    [67, 43, 21, 76, 54],
    [98, 32, 65, 87, 19],
    [44, 55, 66, 77, 88]
])

a = code[0]
b = code[:,-1][::-1]
c = np.diag(code)
d = np.diag(np.fliplr(code))
res = np.concatenate([a,b,c,d])
print(res[10])

10


БУЛЕВА ИНДЕКСАЦИЯ

In [ ]:
import numpy as np

np.random.seed(42)
arr = np.random.randint(0,20,size=15)
print(arr)
mask1 = arr>10
mask2 = arr%2==0
print(arr[mask1])
print(arr[mask2])

[ 1  0 11 11 16  9 15 14 14 18 11 19  2  4 18]
[11 11 16 15 14 14 18 11 19 18]
[ 0 16 14 14 18  2  4 18]


In [ ]:
np.random.seed(42)
arr = np.random.randint(-10,10,size=20)
print(arr)
mask1 = (arr%2==0) & (arr<0)
mask2 = (arr>0) | (arr==0)
mask3 = arr!=5
print(arr[mask1])
print(arr[mask2])
print(arr[mask3])

[ -4   9   4   0  -3  -4   8   0   0  -7  -3  -8  -9   1  -5  -9 -10   1
   1   6]
[ -4  -4  -8 -10]
[9 4 0 8 0 0 1 1 1 6]
[ -4   9   4   0  -3  -4   8   0   0  -7  -3  -8  -9   1  -5  -9 -10   1
   1   6]


In [ ]:
np.random.seed(42)
temperatures = np.random.uniform(-5,5,10)
print(temperatures)
temperatures[temperatures<0]=0
temperatures[temperatures>4]=4
print(temperatures)

[-1.25459881  4.50714306  2.31993942  0.98658484 -3.4398136  -3.4400548
 -4.41916388  3.66176146  1.01115012  2.08072578]
[0.         4.         2.31993942 0.98658484 0.         0.
 0.         3.66176146 1.01115012 2.08072578]


In [ ]:
np.random.seed(42)
matrix = np.random.rand(5,5)
print(matrix)
mask1 = matrix[:,:]>0.5
mask2 = matrix[:,:]>=0.3

rows,cols = np.indices(matrix.shape)
mask3 = (rows == 0) | (rows == matrix.shape[0]-1) | (cols == 0) | (cols == matrix.shape[1]-1)

matrix[mask3]=-1
print(matrix)

[[0.37454012 0.95071431 0.73199394 0.59865848 0.15601864]
 [0.15599452 0.05808361 0.86617615 0.60111501 0.70807258]
 [0.02058449 0.96990985 0.83244264 0.21233911 0.18182497]
 [0.18340451 0.30424224 0.52475643 0.43194502 0.29122914]
 [0.61185289 0.13949386 0.29214465 0.36636184 0.45606998]]
[[-1.         -1.         -1.         -1.         -1.        ]
 [-1.          0.05808361  0.86617615  0.60111501 -1.        ]
 [-1.          0.96990985  0.83244264  0.21233911 -1.        ]
 [-1.          0.30424224  0.52475643  0.43194502 -1.        ]
 [-1.         -1.         -1.         -1.         -1.        ]]


In [ ]:
np.random.seed(42)
ages = np.random.randint(18,26,7)
scores = np.random.randint(0,101,7)
sleep = np.random.randint(4,11,7)
students = np.column_stack((ages,scores,sleep))
mask_score = students[:,1]>=60
mask_sleep = students[:,2]>8
mask_ages = students[:,0]>21
print(students)
print()
print(students[mask_sleep])
print(np.mean(students[mask_sleep][:,1]))

[[24 20  6]
 [21 82  9]
 [22 86  8]
 [24 74  5]
 [20 74  7]
 [25 87  9]
 [22 99  9]]

[[21 82  9]
 [25 87  9]
 [22 99  9]]
89.33333333333333


УНИВЕРСАЛЬНЫЕ ФУНКЦИИ И АГРЕГАЦИЯ

In [ ]:
import numpy as np

a = np.array([10,20,30,40,50])
b = np.array([1,2,3,4,5])

a*b
a/b
a**b
a>25

array([False, False,  True,  True,  True])

In [ ]:
import math as m
corners = np.linspace(0,2*m.pi,20)

np.sin(corners)
np.cos(corners)
exp = np.exp(np.array([1,2,3]))
log = np.log(np.array([1, np.e, np.e**2]))

[0.         0.33069396 0.66138793 0.99208189 1.32277585 1.65346982
 1.98416378 2.31485774 2.64555171 2.97624567 3.30693964 3.6376336
 3.96832756 4.29902153 4.62971549 4.96040945 5.29110342 5.62179738
 5.95249134 6.28318531]


array([0., 1., 2.])

In [ ]:
np.random.seed(42)
data = np.random.randint(1,100,size = (5,5))
print(data)
total_sum = np.sum(data)
min_arg = np.min(data)
max_arg = np.max(data)
mean = np.mean(data)
std = np.std(data)
median = np.median(data)

index = np.unravel_index(np.argmax(data), data.shape)

[[52 93 15 72 61]
 [21 83 87 75 75]
 [88 24  3 22 53]
 [ 2 88 30 38  2]
 [64 60 21 33 76]]
(np.int64(0), np.int64(1))


In [ ]:
np.random.seed(42)
data = np.random.randint(1,100,size = (5,5))
print(data)
sum_cols = np.sum(data,axis = 0)
sum_rows = np.sum(data, axis = 1)
min_from_rows = np.min(data, axis = 1)

[[52 93 15 72 61]
 [21 83 87 75 75]
 [88 24  3 22 53]
 [ 2 88 30 38  2]
 [64 60 21 33 76]]
1238
1238


In [ ]:
np.random.seed(42)
x = np.random.rand(10,3)
mean_x = np.mean(x, axis = 0)
x = x - mean_x
mean = np.mean(x, axis = 0)
print(mean_x)
print(mean)

[0.42969452 0.44710393 0.43899337]
[ 5.55111512e-17 -1.66533454e-17 -3.33066907e-17]


In [ ]:
np.random.seed(42)
x = np.random.rand(10,3)
min_from_cols = np.min(x, axis = 0)
max_from_cols = np.max(x, axis = 0)
print(x)
print()
# print(min_from_cols)
# print(max_from_cols)
x = (x-min_from_cols)/(max_from_cols-min_from_cols)
print(x)

[[0.37454012 0.95071431 0.73199394]
 [0.59865848 0.15601864 0.15599452]
 [0.05808361 0.86617615 0.60111501]
 [0.70807258 0.02058449 0.96990985]
 [0.83244264 0.21233911 0.18182497]
 [0.18340451 0.30424224 0.52475643]
 [0.43194502 0.29122914 0.61185289]
 [0.13949386 0.29214465 0.36636184]
 [0.45606998 0.78517596 0.19967378]
 [0.51423444 0.59241457 0.04645041]]

[[0.40866897 1.         0.74236453]
 [0.69809333 0.14560779 0.11862363]
 [0.         0.90911144 0.60063775]
 [0.83938966 0.         1.        ]
 [1.         0.20615898 0.14659502]
 [0.16183823 0.30496576 0.51795022]
 [0.48280112 0.29097513 0.61226564]
 [0.10513243 0.29195941 0.34642716]
 [0.51395587 0.82202662 0.16592323]
 [0.58906891 0.61478523 0.        ]]


ИЗМЕНЕНИЕ ФОРМЫ И ТРАНСФОРМАЦИЯ ДАННЫХ

In [ ]:
import numpy as np

arr = np.arange(12)
matrix_3x4 = arr.reshape(3,4)
matrix_4x3 = matrix_3x4.reshape(4,3)
tenzor = arr.reshape(2,3,2)

In [ ]:
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
flat = matrix.flatten() #копирование матрицы
raw = matrix.ravel() #представление матрицы

flat[0]=999
raw[0]=888
print(matrix)

[[888   2   3]
 [  4   5   6]
 [  7   8   9]]


In [ ]:
a = np.array([10,20,30,40])
res = a.reshape(-1,1)
res1 = a.reshape(1,-1)
b = np.array([[[1], [2], [3]]])
res = np.squeeze(b)
print(b.shape)
print(res)

(1, 3, 1)
[1 2 3]


In [ ]:
x = np.array([[1,2,3],[4,5,6]])
print(x)
transp = x.T
print(transp)

res = x@transp #матрица грама для объектов

res1 = transp@x #матрица грама для признаков

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]
[[14 32]
 [32 77]]
[[17 22 27]
 [22 29 36]
 [27 36 45]]


In [ ]:
a = np.ones((3,3))
b = np.zeros((3,3))

res1 = np.vstack([a,b]) #добавляет строки(объекты)
res2 = np.hstack([a,b]) #добавляет столбцы(признаки)

x = [1,2,3]
y = [4,5,6]
res3 = np.vstack([x,y])
res4 = np.column_stack([x,y]) #собирает матрцу по столбцам
print(res4)

[[1 4]
 [2 5]
 [3 6]]


In [ ]:
np.random.seed(42)

data = np.arange(20)
res = np.split(data,4) #деление по количеству элементов
res1 = np.split(data, [5,15]) #деление по индексам

matrix = np.random.randint(0,100,size = (10,5))
res2 = np.hsplit(matrix, [4]) #делит матрицу по вертикали
res3 = np.vsplit(matrix, [4]) #делит матрицу по горизонтали

[[51 92 14 71 60]
 [20 82 86 74 74]
 [87 99 23  2 21]
 [52  1 87 29 37]
 [ 1 63 59 20 32]
 [75 57 21 88 48]
 [90 58 41 91 59]
 [79 14 61 61 46]
 [61 50 54 63  2]
 [50  6 20 72 38]]
[array([[51, 92, 14, 71, 60],
       [20, 82, 86, 74, 74],
       [87, 99, 23,  2, 21],
       [52,  1, 87, 29, 37]]), array([[ 1, 63, 59, 20, 32],
       [75, 57, 21, 88, 48],
       [90, 58, 41, 91, 59],
       [79, 14, 61, 61, 46],
       [61, 50, 54, 63,  2],
       [50,  6, 20, 72, 38]])]


ЛИНЕЙНАЯ АЛГЕБРА И ГЕНЕРАЦИЯ СЛУЧАЙНЫХ ЧИСЕЛ

In [1]:
import numpy as np

a = np.array([[1, 2], [3, 4], [5, 6]])
b = np.array([[7, 8, 9, 10], [11, 12, 13, 14]])
res = a@b #перемножение матриц

v = np.array([1, 2, 3]) #вектор строка
w = np.array([4, 5, 6]) #вектор столбец
skal = v@w #для одномерных массивов вычисляется скалярное произведение

In [ ]:
a = np.array([[2,1],[1,-3]])
b = np.array([5,-8])
solutions = np.linalg.solve(a,b)

#решение систем уравнений

c = np.array([[1,2,1],[1,-1,2],[1,1,-1]])
d = np.array([6,3,3])
solv = np.linalg.solve(c,d)

[6. 3. 3.]


In [ ]:
M = np.array([[4, 7], [2, 6]])
det = np.linalg.det(M) #определитель матрицы
M_inv = np.linalg.inv(M) #вычисление обратной матрицы

In [ ]:
s = np.array([[5,2],[2,4]])
eingvalues, eingvector = np.linalg.eig(s)

print(s@eingvector[:,0])
print(s[0]*eingvector[:,0]) #собственные векторы и значения??????????

[5.17185161 4.03805971]
[3.94102719 1.23082442]


In [ ]:
p = np.array([1, 2, 3])
q = np.array([4, 5, 6])

np.linalg.norm(p) #длина вектора
np.linalg.norm(p-q) #расстояние между точками
np.linalg.norm(p, ord=1) #манхеттенское расстояние (dist = |x1-x2|+|y1-y2|)
np.linalg.norm(p-q, ord = np.inf) #расстояние чебышева (dist = max(|x1-x2|,|y1-y2|)

np.float64(3.0)

In [ ]:
np.random.seed(42)

random_int = np.random.randint(1,11,5)
rr_matrix = np.random.rand(3,3) #равномерное распределение
nr_matrix = np.random.randn(4,2) #нормальное распределение
normal_mas = np.random.normal(100,15,100) #массив со средним 100 и стандартным отклонением 15


14.998695088641371


In [ ]:
np.random.seed(42)

data = np.arange(20)
np.random.shuffle(data)

#перемешивание двух связаных массивов (x(100 объектов, 5 признаков), y(100 доп. признаков к x))
x = np.random.randn(100, 5)
y = np.random.randn(100)

indices = np.arange(100)
np.random.shuffle(indices)
x_shuff = x[indices]
y_shuff = y[indices]

#формирование выборки
np.random.choice(data,5,replace = False) #выборка 5 элементов без повторений
np.random.choice(data,5, replace = True) #выборка с повторением

#взвешенная выборка (вероятность событий не равна и задается аргументом)
np.random.choice(['A', 'B', 'C'], size=20, p = [0.9,0.05,0.05])

array(['A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A',
       'A', 'A', 'A', 'C', 'A', 'A', 'A'], dtype='<U1')

In [70]:
np.random.seed(42)

X = np.random.randn(100,3) #100 объектов 3 признака
w_true = np.array([2.5,-1.3,0.8]) #истинные веса (коэфициенты влияющие на целевую переменную)
noise = np.random.normal(0,0.5,100) #шум (помехи, наличие которых симулирует настоящие данные)

y = X@w_true+noise #целевые переменные

#связно перемешиваем данные (y[0] всё также является целевым значением x[0])
indices = np.arange(100)
X_shuffle = X[indices]
y_shuffle = y[indices]

#делим данные на тренировочные и тестовые
split_ind = 80
X_train, X_test = X_shuffle[:split_ind], X_shuffle[split_ind:]
y_train, y_test = y_shuffle[:split_ind], y_shuffle[split_ind:]

#обучение модели через lstsq (????)
w_estimated = np.linalg.lstsq(X_train,y_train,rcond=None)[0]

#предсказываем целевые значения
y_pred = X_test@w_estimated

#считаем среднюю квадратичную ошибку
mse = np.mean((y_pred-y_test)**2)
print(mse)

0.3193057296384286


ФИНАЛЬНЫЙ ПРОЕКТ

In [12]:
import numpy as np
np.random.seed(42)
n = 500

area = np.random.uniform(30,120,n)
rooms = np.random.randint(1,5,n)
floor = np.random.uniform(0,1,n)
year_build = np.random.randint()

[0.11689804 0.93983212 0.62770805 0.33490561 0.13927207 0.79402519
 0.62007276 0.53346109 0.89389258 0.78859721 0.15167488 0.31172207
 0.24848914 0.74394629 0.03353243 0.56988968 0.76245869 0.87676564
 0.34208175 0.8212573  0.11063174 0.84645229 0.12748866 0.39728729
 0.79729537 0.14991743 0.2292514  0.72225257 0.72003654 0.64114763
 0.69394844 0.54272444 0.25179906 0.34569599 0.18159772 0.90845056
 0.58339179 0.40085142 0.4620058  0.94728334 0.1533514  0.58622983
 0.50588868 0.61145424 0.01811018 0.87212391 0.93211828 0.56513318
 0.69665082 0.92249938 0.70723863 0.15253904 0.57628836 0.60671505
 0.42413067 0.73644424 0.93436701 0.92556851 0.45083937 0.11323805
 0.9848412  0.83889809 0.12466268 0.92084188 0.86989636 0.51883806
 0.59127544 0.3990027  0.05476164 0.33519724 0.80285345 0.00463202
 0.33349917 0.39816869 0.5373956  0.91985562 0.34634599 0.3469532
 0.73750125 0.45221794 0.22460482 0.45243952 0.14085702 0.17638699
 0.49836777 0.41892545 0.9148459  0.3623939  0.58058835 0.63226